server:
    port: 8080

kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
    secret: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update # create, create-drop, update, validate 중 선택
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect